# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 5000 for the application
EXPOSE 5000

# Run the development server on port 5000, accessible on all interfaces
CMD ["npm", "run", "dev","--port", "5000"]
